cookie:
  expiry_days: 30
  key: change-me-in-production
  name: nexus_cookie
credentials:
  usernames:
    amin:
      email: muhammaddawoodmoria@gmail.com
      logged_in: false
      name: admin
      password: $2b$12$.dwfUwo6gq/hPUpp59AS0.jzpUt2tYnQ5FrvbIBWQEMTtkcZapGBG
preauthorized:
  emails: []
